# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='e1model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GB_FA_ID', models.CharField(max_length=30)),
                ('GB_FA_PW', models.CharField(max_length=20)),
                ('CTVT_FCLTY_ID', models.CharField(max_length=30)),
                ('GB_FA_PHONE', models.CharField(max_length=13)),
                ('GB_FA_EMAIL', models.CharField(max_length=30)),
                ('GB_FA_ADDR', models.CharField(max_length=100)),
                ('GB_FA_NAME', models.CharField(max_length=20)),
                ('GB_FA_SIZE', models.IntegerField(null=True)),
                ('GB_FAM_NUM', models.IntegerField(null=True)),
                ('GB_COOPER_UNIT', models.CharField(max_length=30)),
            ],
        ),
    ]
