# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='com_infor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CI_CODE', models.CharField(max_length=10)),
                ('CI_NAME', models.CharField(max_length=30)),
                ('CI_ADDR', models.CharField(max_length=100)),
                ('CI_PHONE', models.CharField(max_length=13)),
            ],
        ),
    ]
