# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_com_infor'),
    ]

    operations = [
        migrations.CreateModel(
            name='device_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DA_ID', models.CharField(max_length=10)),
                ('DA_NAME', models.CharField(max_length=20)),
                ('DA_PHONE', models.CharField(max_length=13)),
                ('DA_ROLE', models.CharField(max_length=20)),
                ('CI_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.com_infor')),
            ],
        ),
        migrations.CreateModel(
            name='device_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DC_CODE', models.CharField(max_length=10)),
                ('DC_KIND', models.CharField(max_length=20)),
            ],
        ),
    ]
