# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_gb_info_inner_gh_info_sensor_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GM_WORK_ID', models.IntegerField(null=True)),
                ('GM_WORK_DATE', models.DateField()),
                ('GM_WORK_LINE_NUM', models.IntegerField(null=True)),
                ('GM_LABOR_TIME', models.TimeField()),
                ('GM_WORK_INFO', models.CharField(max_length=50)),
                ('GM_AGRI_MTRI_IN_WORK', models.CharField(max_length=50)),
                ('GM_WORK_CODE', models.CharField(max_length=5)),
                ('GM_WORK_OP', models.CharField(max_length=50)),
                ('CI_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.com_infor')),
                ('FI_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.e1model')),
            ],
        ),
    ]
