# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_work_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_info',
            name='CI_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gb_info'),
        ),
    ]
