# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180603_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='after_harves_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GM_LOT_NUM', models.IntegerField(null=True)),
                ('GM_INFO_PROCESS', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='harves_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GM_HARVES_ID', models.IntegerField(null=True)),
                ('GM_DATE_HARVES', models.DateTimeField()),
                ('GM_HARVES_YIELD', models.FloatField(null=True)),
                ('GM_WEIGHT', models.FloatField(null=True)),
                ('GM_QUALIT_GRAD', models.CharField(max_length=10)),
                ('WI_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.work_info')),
            ],
        ),
        migrations.CreateModel(
            name='mainte_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GM_MAINTE_WORKE_DATE', models.DateTimeField()),
                ('GM_FACITY_NAME', models.CharField(max_length=50)),
                ('GM_MAINTE_INFO', models.CharField(max_length=50)),
                ('GM_REPAIR_COST', models.IntegerField(null=True)),
                ('WI_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.work_info')),
            ],
        ),
        migrations.CreateModel(
            name='sale_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GM_SALE_ID', models.IntegerField(null=True)),
                ('GM_SALE_DATE', models.DateField()),
                ('GM_METHODS_SALE', models.CharField(max_length=30)),
                ('GM_PACK_UNIT', models.CharField(max_length=5)),
                ('GM_GALSE', models.FloatField()),
                ('GM_PRICE_BOX', models.IntegerField()),
                ('GM_TOTAL_INCOME', models.IntegerField()),
                ('HI_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.harves_info')),
            ],
        ),
        migrations.AddField(
            model_name='after_harves_info',
            name='HI_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.harves_info'),
        ),
    ]
