# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180604_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='actuator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GE_ACTION_TIME', models.TimeField()),
                ('GE_TOP_VENT', models.NullBooleanField()),
                ('GE_SIDE_VENT', models.NullBooleanField()),
                ('GE_HORIZN_CURTAN', models.NullBooleanField()),
                ('GE_VERTICAL_CURTAN', models.NullBooleanField()),
                ('GB_INNER_FA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gb_info')),
            ],
        ),
        migrations.CreateModel(
            name='env_inner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GE_IN_TIME', models.TimeField()),
                ('GE_IN_TEMP', models.FloatField()),
                ('GE_IN_HUMI', models.FloatField()),
                ('GE_IN_CO2', models.FloatField()),
                ('GE_IN_SOLAR_RADI', models.FloatField()),
                ('GE_IN_WIND_SPD', models.FloatField()),
                ('GB_INNER_FA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gb_info')),
            ],
        ),
        migrations.CreateModel(
            name='env_outer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GB_OUT_TIME', models.TimeField()),
                ('GE_OUT_TEMP', models.FloatField()),
                ('GE_OUT_HUMI', models.FloatField()),
                ('GE_OUT_WIND_DIRECT', models.FloatField()),
                ('GE_OUT_WIND_SPD', models.FloatField()),
                ('GE_SOLAR_RADI', models.FloatField()),
                ('GE_RAINF', models.FloatField()),
                ('GB_INNER_FA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gb_info')),
            ],
        ),
        migrations.CreateModel(
            name='env_root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GE_ROOT_TIME', models.TimeField()),
                ('GE_GROUND_TEMP', models.FloatField()),
                ('GE_GROUND_HUMI', models.FloatField()),
                ('GE_EC', models.FloatField()),
                ('GE_PH', models.FloatField()),
                ('GB_INNER_FA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gb_info')),
            ],
        ),
        migrations.CreateModel(
            name='nutrient_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GE_SUPPLY_START_TIME', models.TimeField()),
                ('GE_SUPPLY_END_TIME', models.TimeField()),
                ('GE_WATER_OUT', models.FloatField()),
                ('GE_SUPPLY_EC', models.FloatField()),
                ('GE_SUPPLY_PH', models.FloatField()),
                ('GE_SPLY_CONST_CONCEN', models.FloatField()),
                ('GE_FLOW_OUT', models.FloatField()),
                ('GE_DRAIN_EC', models.FloatField()),
                ('GE_DRAIN_PH', models.FloatField()),
                ('GE_DRAIN_CONST_CONCEN', models.FloatField()),
                ('GB_INNER_FA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gb_info')),
            ],
        ),
        migrations.CreateModel(
            name='onoff_act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GB_EVENT_TIME', models.TimeField()),
                ('GE_FAN', models.NullBooleanField()),
                ('GE_SUPPORT_LIGHT', models.NullBooleanField()),
                ('GE_HEAT', models.NullBooleanField()),
                ('GE_IRRIGA', models.NullBooleanField()),
                ('GE_CO2_GE', models.NullBooleanField()),
                ('GE_FOG', models.NullBooleanField()),
                ('GB_INNER_FA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gb_info')),
            ],
        ),
    ]
